In [ ]:
!pip install -U spacy
!pip install -U matplotlib
!pip3 install  beautifulsoup

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 9.4 MB 35.7 MB/s 
     |████████████████████████████████| 965 kB 68.7 MB/s 
     |████████████████████████████████| 295 kB 82.0 MB/s 
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement beautifulsoup (from versions: 3.2.0, 3.2.1, 3.2.2)
ERROR: No matching distribution found for beautifulsoup


In [ ]:
!python -m spacy download en_core_web_sm

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 12.8 MB 29.6 MB/s 
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')


In [ ]:
from __future__ import unicode_literals, print_function, division
from io import open
import glob
import os
import random
random.seed(12)

from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

Mounted at /content/drive/


**PART 1: LSTM FOR LANGUAGE MODELING**

**Task 1:** Follow the tutorial in [here](https://www.analyticsvidhya.com/blog/2020/08/build-a-natural-language-generation-nlg-system-using-pytorch/) to train a word-level LSTM language model. Train the language model on texts
from the file prideAndPrejudice.txt. Before using it to train the language model, you need to first sentence-segment, then
tokenize, then lower case each line of the file using Spacy. Append start-of-sentence token ’\<s\>’ and end-of-sentence
’\</s\>’ token to each sentence and put each sentence in its own line. Use only words that appear more than once in this
corpus and assign UNK tokens for the rest; you may also need to pad sentences that are shorter than 5 (see [here](https://github.com/gabrielloye/LSTM_Sentiment-Analysis/blob/master/main.ipynb) in cell
10-12 for adding unknown: UNK token and padding: PAD token to your vocabulary). Train the language model and
save the trained model (see [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html)). Generate 10 examples of text from it, starting from ’\<s\>’ token and ending at ’\</s\>’
token.

**Checkpoint 1:**

Load texts from by lines. The samples of your loaded text lines should look like the following.

In [ ]:
def findFiles(path): return glob.glob(path)

print(findFiles('/content/drive/MyDrive/Colab Notebooks/CS_505_rs_prjt/*.txt'))

import unicodedata
import string

all_letters = string.ascii_letters + " .,;'"
n_letters = len(all_letters)

# Turn a Unicode string to plain ASCII, thanks to https://stackoverflow.com/a/518232/2809427
def unicodeToAscii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
        and c in all_letters
    )

print(unicodeToAscii('Ślusàrski'))

# Build the category_lines dictionary, a list of names per language
all_categories = []

# Read a file and split into lines
def readLines(filename):
    lines = open(filename, encoding='utf-8').read().strip().split('\n')
    return [line for line in lines]

for filename in findFiles('/content/drive/MyDrive/Colab Notebooks/CS_505_rs_prjt/*.txt'):
    novel = os.path.splitext(os.path.basename(filename))[0]
    all_categories.append(novel)
    lines = readLines(filename)


n_categories = len(all_categories)

['/content/drive/MyDrive/Colab Notebooks/CS_505_rs_prjt/the_star_of_gettysburg-pg3811.txt']
Slusarski


In [ ]:
print(all_categories)
print([lines[695],lines[0]])

n = 5
random.sample(lines, n)

['the_star_of_gettysburg-pg3811']
['for May-day."', '\ufeffThe Project Gutenberg EBook of The Star of Gettysburg, by Joseph A. Altsheler']


['all the while, and that morning the doctor informed his wife that he was',
 '"You\'re right, Harry," said Dalton, as he replaced the doll and closed',
 'He heard Lee say to an officer who rode up, and stated, between sobbing',
 'the horsemen of the South that those of the North were on the watch.',
 '']

In [ ]:
lines_dict = dict(enumerate(lines))
print(lines_dict)

{0: '\ufeffThe Project Gutenberg EBook of The Star of Gettysburg, by Joseph A. Altsheler', 1: '', 2: 'This eBook is for the use of anyone anywhere at no cost and with', 3: 'almost no restrictions whatsoever.  You may copy it, give it away or', 4: 're-use it under the terms of the Project Gutenberg License included', 5: 'with this eBook or online at www.gutenberg.org', 6: '', 7: '', 8: 'Title: The Star of Gettysburg', 9: '       A Story of Southern High Tide', 10: '', 11: 'Author: Joseph A. Altsheler', 12: '', 13: 'Posting Date: May 28, 2009 [EBook #3811]', 14: 'Release Date: March, 2003', 15: 'First Posted: September 19, 2001', 16: 'Last Updated: May 25, 2004', 17: '', 18: 'Language: English', 19: '', 20: '', 21: '*** START OF THIS PROJECT GUTENBERG EBOOK THE STAR OF GETTYSBURG ***', 22: '', 23: '', 24: '', 25: '', 26: 'Produced by Ken Reeder.  HTML version by Al Haines.', 27: '', 28: '', 29: '', 30: '', 31: '', 32: '', 33: '', 34: '', 35: '', 36: 'Errata and other transcription notes 

**Checkpoint 2:**

Preprocess your loaded texts with spacy, also convert words into lower-case, and also pad sentences with \<s\> and \</s\>. The preprocessed lines should look like the following.

In [ ]:
import re
import spacy
from tqdm import tqdm

In [ ]:




import requests
from bs4 import BeautifulSoup

data = []

# Make a request
# page = requests.get('https://www.gutenberg.org/cache/epub/3811/pg3811-images.html')
# page = requests.get('https://en.wikipedia.org/wiki/The_Killer_Angels')
page = requests.get('http://www.script-o-rama.com/movie_scripts/g/gettysburg-script-transcript-civil-war.html')
soup = BeautifulSoup(page.content, 'html.parser')

data.append({
    'book': soup.h2.get_text(),
    'table' : soup.find("pre").find(text=True),
    'text': ' '.join([p.get_text(strip=True) for p in soup.select('body p')[2:]])
    }
)

data[0]['table']

'\n\n \n\n                   \n\nIn June 1863 after more than two years\n\nof bloody conflict...\n\n\n\n \n\n                   \n\nthe Confederate army of Northern\n\nVirginia, Robert E. Lee commanding...\n\n\n\n \n\n                   \n\nslips across the Potomac\n\nto begin the invasion of the North.\n\n\n\n \n\n                   \n\nIt is an army of       men.\n\n\n\n \n\n                   \n\nThey move slowly behind the Blue Ridge...\n\n\n\n \n\n                   \n\nusing the mountains\n\nto screen their movements.\n\n\n\n \n\n                   \n\nTheir objective is to draw\n\nthe Union army out into the open...\n\n\n\n \n\n                   \n\nwhere it can be destroyed.\n\n\n\n \n\n                   \n\nLate in June, the Union army\n\nof the Potomac,       men...\n\n\n\n  \n\n                   \n\nturns north from Virginia to begin\n\nthe great pursuit up the narrow roads...\n\n\n\n  \n\n                   \n\nacross Maryland and into Pennsylvania.\n\n\n\n  \n\n        

In [ ]:
def remove_extras(in_texts):
    textList = []
    for in_text in in_texts:
        t_en = in_text.encode("ascii", "ignore")
        t = t_en.decode()
        t = re.sub("\n", " ", t)
        t = re.sub("\r", " ", t)
        t = re.sub("&lt;", "<", t)
        t = re.sub("&gt;", ">", t)
        t = re.sub("&amp;", "&", t)
        t = re.sub(r'(https|http)?:\/\/(\w|\.|\/|\?|\=|\&|\%)*\b', '', t, flags=re.MULTILINE) # URLs
        t = re.sub(r'@[\w]+','', t, flags=re.MULTILINE) # mentions
        t = re.sub(r'#[\w]+','', t, flags=re.MULTILINE) # hashtags
        t = re.sub("[!@#$%^&*()[]{};:,/<>\|`~-=_+]", " ", t)
        t = re.sub(r"([.!?])", r" \1", t)
        textList.append(t)
    return textList


def preprocess(tweetDict, batchsz=500):
    # Input: a wiki text dictionary with keys are titles and values are the corresponding texts.
    # Output: a wiki text dictionary with keys are the titles and the values are the preprocessed texts
    # (sentences - tokens).

    # sub-task 1: remove all the references texts "[...]"
    # sub-task 2: segment all the sentences in the wiki texts.
    # sub-task 3: tokenize the sentences from sub-task 2.
    # sub-task 4: lemmatize the tokens from sub-task 3.
    # sub-task 5: lower-case the tokens from sub-task 3/4.


    texts = list(tweetDict.values())
    clean_texts = remove_extras(texts) # Step 1
    print(clean_texts)
    clean_texts2 = []
    print(len(clean_texts), len(clean_texts[0]))
    nlp = spacy.load('en_core_web_sm')
    print(nlp.pipe_names)
    docsDict = {}
    docsSpanDict = {}
    docsEntDict = {}
    cnt = 0
    # pipeline accomplishes steps [2-4]
    for doc in tqdm(nlp.pipe(clean_texts, batch_size=batchsz)):
        docSpanList = []
        docList = []
        docEntList = []
        # print(list(doc.sents), type(doc))
        clean_texts2.append(list(doc.sents))
        for ent in doc.ents:
            #  THIS LINE GIVES THE NAMED ENTITIES IN DOC

            if ent.label_ == 'GPE' or ent.label_ == 'PERSON':
                print(ent.text, ent.start_char, ent.end_char, ent.label_)
                docEntList.append(str(ent.text) + '|' + str(ent.label_))
        if docEntList:
            docsEntDict[list(tweetDict.keys())[cnt]] = docEntList
        for spanText in doc.sents:
            spanList = []
            # print(spanText.text, type(spanText))
            for tok in spanText: 
                # print(f' token lemma {tok.lemma_} {tok.text}')
                docList.append(tok.text.lower()) # step 5
                spanList.append(tok.text.lower())
            docSpanList.append(spanList)
            # print(spanList)
        docsDict[list(tweetDict.keys())[cnt]] = docList
        docsSpanDict[list(tweetDict.keys())[cnt]] = docSpanList
        # print(docSpanList)
        cnt += 1
    # print(clean_texts2)
    # print(docsDict)
    return docsDict, docsSpanDict, docsEntDict



In [ ]:
lines_book = {}
lines_book[0]=data[0]['table']
docets, spansdict, docsEnt = preprocess(lines_book)


['                          In June 1863 after more than two years  of bloody conflict . . .                            the Confederate army of Northern  Virginia, Robert E . Lee commanding . . .                            slips across the Potomac  to begin the invasion of the North .                            It is an army of       men .                            They move slowly behind the Blue Ridge . . .                            using the mountains  to screen their movements .                            Their objective is to draw  the Union army out into the open . . .                            where it can be destroyed .                            Late in June, the Union army  of the Potomac,       men . . .                             turns north from Virginia to begin  the great pursuit up the narrow roads . . .                             across Maryland and into Pennsylvania .                             General Lee knows that a letter has been  prepared by the Southern g

0it [00:00, ?it/s]

Northern  Virginia 142 160 GPE
Robert E 162 170 PERSON
Lee 173 176 PERSON
Virginia 771 779 GPE
Maryland 869 877 GPE
Pennsylvania 887 899 GPE
Lee 938 941 PERSON
Abraham Lincoln 1131 1146 PERSON
Lee 1219 1222 PERSON
Washington 1315 1325 GPE
Lee 1583 1586 PERSON
Harrison 2184 2192 PERSON
Harrison 2297 2305 PERSON
Jeb Stuart 4062 4072 PERSON
mule 4509 4513 PERSON
Jeb Stuart's 4711 4723 PERSON
Sorrel 5054 5060 GPE
Lee 5128 5131 PERSON
Eleventh 5715 5723 PERSON
Harrison 5952 5960 PERSON
Mississippi 6042 6053 GPE
George Meade's 6425 6439 PERSON
Harrison 6461 6469 PERSON
George Meade 6529 6541 PERSON
Pennsylvania 6543 6555 GPE
Chamberlain 7359 7370 PERSON
bucko 7433 7438 GPE
Maine 8882 8887 GPE
Maine 9158 9163 GPE
Maine 9411 9416 GPE
George Meade 9664 9676 PERSON
Maine 10274 10279 GPE
Maine 10433 10438 GPE
Moxley 11300 11306 PERSON
Maine 11562 11567 GPE
Lawrence 12284 12292 GPE
Tom 12409 12412 PERSON
Lawrence 12429 12437 PERSON
Maine 12880 12885 GPE
Pennsylvania 13156 13168 GPE
Chamberlain 140

1it [00:04,  4.96s/it]

 154140 PERSON
Gospel 154149 154155 PERSON
George 154222 154228 PERSON
Lee 154855 154858 PERSON
Sam Hood 155196 155204 PERSON
Dick Garnett 155286 155298 PERSON
Winn 156229 156233 PERSON
California 156345 156355 GPE
Garnett 156845 156852 PERSON
Myra 157574 157578 PERSON
Pete 157839 157843 PERSON
Sharpsburg 158634 158644 GPE
Fredericksburg 158646 158660 GPE
Peter 159100 159105 PERSON
Myra Hancock 159205 159217 PERSON
Pete 159496 159500 PERSON
Lee 160674 160677 PERSON
Lee 161986 161989 PERSON
Goodnight 163411 163420 GPE
Pickett 165296 165303 PERSON
Richmond 167252 167260 GPE
Pickett 168222 168229 PERSON
Rice 168589 168593 PERSON
Rice 168801 168805 PERSON
Rice 169038 169042 PERSON
Pettigrew 169895 169904 PERSON
Trimble 169917 169924 PERSON
Pickett 170086 170093 PERSON
Fredericksburg 171581 171595 GPE
Alexander 171783 171792 PERSON
Alexander 172492 172501 PERSON
Fredericksburg 172542 172556 GPE
Hill 172812 172816 PERSON
Hill 172874 172878 PERSON
Hill 172985 172989 PERSON
George 173499 17350

In [ ]:
freqToken = {}
cnt = 0

for j in docsEnt.values():
    for k in j:
        if k not in freqToken:
            freqToken[k] = 1
        else:
            freqToken[k] += 1

freqToken

{k: v for k, v in sorted(freqToken.items(), key=lambda item: item[1])}
# # create integer-to-token mapping
# int2token = {}
# cnt = 0

# for w in set(" ".join(list(docsEnt.values())).split()):
#   int2token[cnt] = w
#   cnt+= 1

# # create token-to-integer mapping
# token2int = {t: i for i, t in int2token.items()}

# token2int["the"], int2token[14271]

{'Northern  Virginia|GPE': 1,
 'Robert E|PERSON': 1,
 'Maryland|GPE': 1,
 'Abraham Lincoln|PERSON': 1,
 'Jeb Stuart|PERSON': 1,
 'mule|PERSON': 1,
 'Sorrel|GPE': 1,
 'Mississippi|GPE': 1,
 "George Meade's|PERSON": 1,
 'bucko|GPE': 1,
 'Moxley|PERSON': 1,
 'Sergeant Tozier|PERSON': 1,
 'Bucklin|GPE': 1,
 'Joseph Bucklin|PERSON': 1,
 'johnny detail|PERSON': 1,
 'Dan Burns|PERSON': 1,
 'Orono|PERSON': 1,
 'America|GPE': 1,
 'Harrisburg|GPE': 1,
 'Glazier|PERSON': 1,
 "Lee'll|PERSON": 1,
 'Gettysburg|PERSON': 1,
 'Carlisle|GPE': 1,
 'Lucy|PERSON': 1,
 'Abe Lincoln|PERSON': 1,
 'Traveler|PERSON': 1,
 'Tell Devin|PERSON': 1,
 'Harry Heth|PERSON': 1,
 'Rodes|GPE': 1,
 'Dan Butterfield|PERSON': 1,
 'Us|GPE': 1,
 'Harvard Yard|PERSON': 1,
 'Manassas|GPE': 1,
 'nightfall|PERSON': 1,
 'Marshall|PERSON': 1,
 'Billy Yank|PERSON': 1,
 'Johnny Reb|PERSON': 1,
 'a John Henry|PERSON': 1,
 'John Henry|PERSON': 1,
 'Negroes|GPE': 1,
 'Bangor|GPE': 1,
 'Portland|GPE': 1,
 'James|PERSON': 1,
 'Sally|PERSON

In [ ]:
docets.values()

dict_values([['                          ', 'in', 'june', '1863', 'after', 'more', 'than', 'two', 'years', ' ', 'of', 'bloody', 'conflict', '.', '.', '.', '                           ', 'the', 'confederate', 'army', 'of', 'northern', ' ', 'virginia', ',', 'robert', 'e', '.', 'lee', 'commanding', '.', '.', '.', '                           ', 'slips', 'across', 'the', 'potomac', ' ', 'to', 'begin', 'the', 'invasion', 'of', 'the', 'north', '.', '                           ', 'it', 'is', 'an', 'army', 'of', '      ', 'men', '.', '                           ', 'they', 'move', 'slowly', 'behind', 'the', 'blue', 'ridge', '.', '.', '.', '                           ', 'using', 'the', 'mountains', ' ', 'to', 'screen', 'their', 'movements', '.', '                           ', 'their', 'objective', 'is', 'to', 'draw', ' ', 'the', 'union', 'army', 'out', 'into', 'the', 'open', '.', '.', '.', '                           ', 'where', 'it', 'can', 'be', 'destroyed', '.', '                           ', 

In [ ]:

from nltk.lm.preprocessing import pad_both_ends
book_text = []
for i in docs.values():
    book_text.append(" ".join(pad_both_ends(i, n=2)))
print(book_text)


NameError: ignored

**Checkpoint 3:**

Define a function to prepare fixed-length sequences from our dataset. Here we specified the length of the sequence as five. You may refer to the tutorial to see how this can be done. Remember to deal with the case of tokens of length less or equal to 5. The following example show what the fixed-length sequence should look like given  input texts. Also compare the size of the processed sequences to see if the number is close.

NOTE: the example is just the processed result of one line, your result sequences should contain processed results for all lines.

In [ ]:
# create sequences of length 5 tokens
def create_seq(text, seq_len = 5):
    
    sequences = []

    # if the number of tokens in 'text' is greater than 5
    if len(text.split()) > seq_len:
      for i in range(seq_len, len(text.split())):
        # select sequence of tokens
        seq = text.split()[i-seq_len:i+1]
        # add to the list
        sequences.append(" ".join(seq))

      return sequences

    # if the number of tokens in 'text' is less than or equal to 5
    else:
      
      return [text]

In [ ]:
seqs = [create_seq(i) for i in book_text]

# merge list-of-lists into a single list
seqs = sum(seqs, [])

# count of sequences
print(f'lines size: {len(seqs)}'), seqs[0]


lines size: 93329


(None, '<s> the project gutenberg ebook of')

<s> " oh ! " said lydia stoutly , " i am not afraid ; for though i _ am _ the youngest , i 'm the tallest . " </s>
['<s> " oh ! " said', '" oh ! " said lydia', 'oh ! " said lydia stoutly', '! " said lydia stoutly ,', '" said lydia stoutly , "', 'said lydia stoutly , " i', 'lydia stoutly , " i am', 'stoutly , " i am not', ', " i am not afraid', '" i am not afraid ;', 'i am not afraid ; for', 'am not afraid ; for though', 'not afraid ; for though i', 'afraid ; for though i _', '; for though i _ am', 'for though i _ am _', 'though i _ am _ the', 'i _ am _ the youngest', '_ am _ the youngest ,', 'am _ the youngest , i', "_ the youngest , i 'm", "the youngest , i 'm the", "youngest , i 'm the tallest", ", i 'm the tallest .", 'i \'m the tallest . "', '\'m the tallest . " </s>']
lines size:  6004
sequences size:  126698


**Checkpoint 4:**

Create inputs and targets (x and y) for training; a sample of your x and y should look like the following. Remember to pad sequences with less than 5 tokens. (NOTE: the sample is just a pair of x,y, not all x's /y's for inputs and targets).

sample x:  " for mrs. long has
sample y:  for mrs. long has just


**Checkpoint 5:**

Compute a list of all words that need to be assigned as UNK. Part of the unknown list should look like the following.

['unwearying', 'defended', 'pointedly', 'although', 'utterly', 'resisted', 'gratification', 'chimney', 'digressions', 'improvements', 'retail', 'imitations', 'china', 'broad', 'faced', 'stuffy', 'breathing', 'port', 'commonest', 'dullest', 'topic', 'speaker', 'rivals', 'muffin', 'life--', 'compliance', 'engrossing', 'talker', 'bets', 'prizes', 'demands', 'hesitating', 'anywhere', 'estimated', 'imposing', 'proclaim', 'breathed', 'truest', 'verily', 'topics', 'military', 'bequeathed', 'gift', 'godfather', 'heavens', 'disregarded', 'legal', 'redress', 'informality', 'bequest', 'conditional', 'forfeited', 'disgraced', 'irritated', 'inhumanity', 'boasting', 'implacability', 'resentments', 'amiable"--but', 'childhood', 'inmates', 'parental', 'confidential', 'superintendence', 'providing', 'dishonest', 'dishonesty', 'impulses', 'degenerate', 'popular', 'guardian', 'superintends', 'trials', 'reverting', 'conversible', 'equals', 'chances', 'shillings', 'regarding', 'misleads', 'arrogant', 'dict

**Checkpoint 6:**

Build two dictionaries (vocabulary), one maps a unique integer to a unique token. The other one is a mapping from the reversed direction. The following is an example of the key-value pairs of the two dictionaries. Your dictionaries should have similar formats.

key: 'the' value:  1502
key: 1327, value:  the
size of the dictionaries (vocabulary): 3907 and 3907


**Checkpoint 7:**

Add unknown and padding to the two dictionaries (check). The size of them should increase by 2.

vocabulary sizes: 3909,3909
token2int['_PAD'] 3908
token2int['_UNK'] 3907


**Checkpoint 8:**

Convert your sequences of tokens into integers, with the dictionaries we just built. Your x's and y's should look like the following.

x in integers: 
[[2514 3142 1934 1341 3284]
 [3142 1934 1341 3284 2482]
 [1934 1341 3284 2482  645]
 ...
 [1002 1502 1824  148 3907]
 [1502 1824  148 3907  533]
 [1824  148 3907  533  322]]

y in integers: 
[[3142 1934 1341 3284 2482]
 [1934 1341 3284 2482  645]
 [1341 3284 2482  645 3167]
 ...
 [1502 1824  148 3907  533]
 [1824  148 3907  533  322]
 [ 148 3907  533  322 1356]]


**Checkpoint 9:**

Build your LSTM model with Pytorch. Your LSTM structure should look like the following:



WordLSTM(
  (emb_layer): Embedding(3909, 200)
  (lstm): LSTM(200, 256, num_layers=4, batch_first=True, dropout=0.3)
  (dropout): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=256, out_features=3909, bias=True)
)


**Checkpoint 10:**

Train your model with the processed data.

**Checkpoint 11:**

Generate 10 examples of text from the model, starting from ’\<s\>’ token and ending at ’\</s\>’ token. The generated texts should look more or less natural, instead of being in a very fixed pattern or randomly generated. Some examples are shown below.

<s> " i have been in the world . ' </s>
<s> she was not to have been a very agreeable man , and she could have been in a _UNK manner , " cried elizabeth . ' </s>
<s> i do assure her to the other side , and _UNK her education ; and , in the _UNK . ' i am afraid he had done , and the _UNK , i believe , to be _UNK . ' i have been so well concealed ; for she had not been in the least unwilling to make a very _UNK eye ; but i have been in the least altered by the _UNK , i believe you are to see him at longbourn ; but , and , and the two sisters , " she added : ' i hope i should not have been so _UNK . </s>
<s> " oh ; " and i do , " said she ; but , and she had no idea , and she had no more _UNK to the _UNK of his friend , and the others are not _UNK . </s>
<s> i have not the honour , and she had not seen them . ' </s>
<s> i do , " replied her father , and the others are to be done , but i am afraid i have been so fortunate in love with you . </s>
<s> i do , " cried jane ; but i have not see

**Task 2:**

Compute and report the perplexity of the saved model on test_1.txt and test_2.txt files. Note that the test files are already preprocessed. Compute the complexity of the test_2.txt by saving the model first and then loading it.

**Checkpoint 1:**

Load your test_1.txt file in lines as you did in task 1. The results should look similar to the following.

['<s> the family of dashwood had long been settled in sussex . </s>', '<s> their estate was large , and their residence was at norland park , in the centre of their property , where , for many generations , they had lived in so respectable a manner as to engage the general good opinion of their surrounding acquaintance . </s>', '<s> the late owner of this estate was a single man , who lived to a very advanced age , and who for many years of his life , had a constant companion and housekeeper in his sister . </s>', '<s> but her death , which happened ten years before his own , produced a great alteration in his home ; for to supply her loss , he invited and received into his house the family of his nephew mr. henry dashwood , the legal inheritor of the norland estate , and the person to whom he intended to bequeath it . </s>', "<s> in the society of his nephew and niece , and their children , the old gentleman 's days were comfortably spent . </s>", '<s> his attachment to them all incre

**Checkpoint 2:**

Compute the perplexity on test_1.txt. Your final perplexity should look like the one below. (You may need to implement the perplexity calculation on your own instead of using any existing ones from libraries.)

perplexity on test_1.txt is:  172.75867345155558


**Checkpoint 3:**

Save your model with the 'state_dict()' method. Load your saved model and sample some generated texts to see if it works properly. The sample texts could look like the following one.

'<s> " oh , yes ! pray be _UNK , i am afraid of her , she could not be insensible to the latter method , " said elizabeth ; and she had no reason , i am sure i have not a little mistake , and the _UNK _UNK of his _UNK , she could not help cautioning her to see her ; for she was not in a very different _UNK . " </s>'

**Checkpoint 4:**

Load your test_2.txt file in lines. Compute the perplexity with your loaded model. The perplexity should look close to (or better than) the following one.

perplexity on test_2.txt is:  951.2221688812576


**Task 3:**

Train the language model as before, but with input sequence lengths of 25 (currently, its inputs are of length 5).
You may need to pad some of the shorter sentences to length 25. Save your trained model. Generate 10 examples of text
from it, starting from ’\<s\>’ token and ending at ’\</s\>’ token. **Answer in a separate cell:** Are there differences from the generated examples from
2.1? 

**Task 4:**
Compute and report the perplexity of this saved model on test 1.txt file. **Answer in a separate cell:** Is there any reason why this model is better/worse than the previous one (length = 5)?

NOTE: at this point you should be able to finish the tasks without the checkpoints, try to re-use the code you've implemented.

**Task 5:**

Train the better language model as before but start with pre-trained Glove6B 100d embeddings (see [here](https://medium.com/@martinpella/how-to-use-pre-trained-word-embeddings-in-pytorch-71ca59249f76) on how
to incorporate pretrained embeddings in your LSTM model). This time, use all your words in the corpus as vocabulary,
even those occurring only once in the corpus. Only assign UNK token to words that are not in the Glove vocabulary and
initialize random vectors in the embedding matrix for the UNK, \<s\>, \</s\>, and PAD tokens using a Gaussian
distribution with mean 0.0 and σ set to 0.6 (see numpy.random.normal). Save your trained model. Generate 10 examples of text from it,
starting from the ’\<s\>’ token and ending at the ’\</s\>’ token. Are there differences from the generated examples from before?

**Task 6:**
Compute and report the perplexity of this saved model on the test 1.txt file.

NOTE: 

1. The biggest difference between this task and the previous starts from the word-integer dictionary. In addition to the mappings between word and integer, you also need to have a dictionary that maps the word to the word vector in Glove. Don't forget to add UNK, PAD, \<s\> and \</s\> to the dictionary. As these tokens do not exist in Glove, you need np.random.normal(...) to assign them random values.
2. The next difference is since the most of the word embeddings are pre-trained, you need to initialize nn.Embed with the Glove embedding matrix. You also need to adjust the model to fit the embedding as well.
3. The training might take a very long time, make sure you have your GPU utilized for Pytorch and get enough time running it.